apiVersion: v1
kind: Namespace
metadata:
  name: trading-research
  labels:
    trading-environment: research
---
apiVersion: v1
kind: Namespace
metadata:
  name: trading-paper
  labels:
    trading-environment: paper
---
apiVersion: v1
kind: Namespace
metadata:
  name: trading-testnet
  labels:
    trading-environment: testnet
---
apiVersion: v1
kind: Namespace
metadata:
  name: trading-live
  labels:
    trading-environment: live
---
apiVersion: v1
kind: Namespace
metadata:
  name: trading-monitoring
  labels:
    trading-environment: monitoring
