apiVersion: v1
kind: ServiceAccount
metadata:
  name: research
  namespace: trading-research
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paper
  namespace: trading-paper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testnet
  namespace: trading-testnet
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: live
  namespace: trading-live
